### ISSUE TITLE
Sharing iP code quality feedback [for @linuschancs]

### ISSUE THREAD

**Issue by nus-se-script** [linuschancs/ip#4]
@linuschancs We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/betago/TaskList.java` lines `197-202`](https://github.com/linuschancs/ip/blob/cfecff26e9394c887d25b09aafd5cc2ee7c3d5bd/src/main/java/betago/TaskList.java#L197..L202):

```java

    /**
     * Read todo task from the data file and add a todo task accordingly into the TaskList.
     *
     * @param str Line of text from the data file to load task.
     * @throws DukeException If marker is not 1 or 0, or str is of the wrong format.
     */

```

Example from [`src/main/java/betago/TaskList.java` lines `219-224`](https://github.com/linuschancs/ip/blob/cfecff26e9394c887d25b09aafd5cc2ee7c3d5bd/src/main/java/betago/TaskList.java#L219..L224):

```java

    /**
     * Read deadline task from the data file and add a deadline task accordingly into the TaskList.
     *
     * @param str Line of text from the data file to load task.
     * @throws DukeException If marker is not 1 or 0, or str is of the wrong format.
     */

```

Example from [`src/main/java/betago/TaskList.java` lines `254-259`](https://github.com/linuschancs/ip/blob/cfecff26e9394c887d25b09aafd5cc2ee7c3d5bd/src/main/java/betago/TaskList.java#L254..L259):

```java

    /**
     * Read event task from the data file and add an event task accordingly into the TaskList.
     *
     * @param str Line of text from the data file to load task.
     * @throws DukeException If marker is not 1 or 0, or str is of the wrong format.
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message (Subject Only)

possible problems in commit [`8cd5e5b`](https://github.com/linuschancs/ip/commit/8cd5e5bea2fa6d53917727957601b5323866d21e):

`Merged branch-A-Assertions with master`

* Not in imperative mood (?)
             

**Suggestion:** Follow the given [conventions for Git commit messages](https://se-education.org/guides/conventions/git.html) for _future_ commits (no need to modify past commit messages).

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by linuschancs** [comment]
Fixed Header Comment Issue and future commits are committed in imperative mood.
